apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      service: metrics-engine
  template:
    metadata:
      labels:
        service: metrics-engine
    spec:
      containers:
      - name: metrics-engine
        image: metrics-engine:latest
        imagePullPolicy: Never
        env:
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672"
        - name: REDIS_URL
          value: "redis:6379"
