global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'metrics-engine'
    static_configs:
      - targets: ['odto-integ-metrics-engine:8080']

  - job_name: 'gateway'
    static_configs:
      - targets: ['odto-integ-gateway:3000']

  - job_name: 'read-model'
    static_configs:
      - targets: ['odto-integ-read-model:8080']

  - job_name: 'web-pty-server'
    static_configs:
      - targets: ['odto-integ-web-pty:9001']
